### ISSUE TITLE
[Bug]: အေမီစျန် <=> Ami Zan

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#14]
### What happened?

**Convert to Myan-glish Name**
input => အေမီစျန်
response result => Mi
expected result => Ami Zan

**Convert to Myanmar Name**
input: Ami Zan
response result: ဇံ
expected result => အေမီစျန်

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'အေမီစျန်';
MMName::convertToEn($name);
```

**Convert to Myanmar Name**
```php
$name = 'Ami Zan'
MMName::convertToMm($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
