### ISSUE TITLE
[Bug]: Empty string when "တင်ဥက္ကာ" convert to EN 

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#15]
### What happened?

Convert to EN
input: တင်ဥက္ကာမောင်
response result: Maung
expected result: Tin Oakkar Maung

### How to reproduce the bug

```
$name = 'တင်ဥက္ကာမောင်';
MMName::convertToEn($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
