### ISSUE TITLE
[Bug]: July Moe <=> ဇူလိုင်မိုး

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#16]
### What happened?

Convert to Myan-glish Name
input: ဇူလိုင်မိုး
response result: Zu Ly Moe
expected result: July Moe

Convert to Myanmar Name
input: July Moe
response result: မိုး
expected result: ဇူလိုင်မိုး

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'ဇူလိုင်မိုး';
MMName::convertToEn($name);
```

**Convert to Myanmar Name**
```php
$name = 'July Moe'
MMName::convertToMm($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
