### ISSUE TITLE
[Bug]: Empty string when "April" convert to MM 

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#17]
### What happened?

**Convert to Myanmar Name**
input: Daw April
response result: ဒေါ်
expected result: ဒေါ်ဧပြီ

### How to reproduce the bug

**Convert to Myanmar Name**
```php
$name = 'Daw April'
MMName::convertToMm($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
