### ISSUE TITLE
[Bug]: Victor - ဗစ်တာခင်ညို <=> Victor Khin Nyo

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#18]
### What happened?

**Convert to Myan-glish Name**
input: ဗစ်တာခင်ညို
response result: Vic Tar Khin Nyo
expected result: Victor Khin Nyo

**Convert to Myanmar Name**
input: Victor Khin Nyo
response result: ခင်ညို
expected result: ဗစ်တာခင်ညို

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'ဗစ်တာခင်ညို';
MMName::convertToEn($name);
```

**Convert to Myanmar Name**
```php
$name = 'Victor Khin Nyo'
MMName::convertToMm($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
