### ISSUE TITLE
[Bug]: Htate Htar

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#19]
### What happened?

**Convert to Myanmar Name**
input: Htate Htar
response result: ထိပ်ထာရ်
expected result: ထိပ်ထား

### How to reproduce the bug

**Convert to Myanmar Name**
```php
$name = 'Htate Htar'
MMName::convertToMm($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
