### ISSUE TITLE
[Bug]: ဒေါ် + ဥမ္မာ

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#21]
### What happened?

**Convert to Myan-glish Name**
input: ဒေါ်ဥမ္မာ
response result: empty string
expected result: Daw Ohnmar

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'ဒေါ်ဥမ္မာ';
MMName::convertToEn($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
