### ISSUE TITLE
[Bug]: သီတာ

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#22]
### What happened?

**Convert to Myan-glish Name**
input: သီတာ
response result: Thi Tar
expected result: Thida

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'သီတာ';
MMName::convertToEn($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
