### ISSUE TITLE
[Bug]: သန္တာ + ဥ + ီ + း

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#23]
### What happened?

**Convert to Myan-glish Name**
input: ဒေါ်သန္တာဦး
response result: Daw
expected result: Daw Thandar Oo

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'ဒေါ်သန္တာဦး';
MMName::convertToEn($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
