### ISSUE TITLE
[Bug]: ဆလိုင်း <=> Salai

### ISSUE THREAD

**Issue by tintnaingwinn** [ageekdev/myanmar-name-converter#24]
### What happened?

**Convert to Myan-glish Name**
input: ဆလိုင်း
response result: Line
expected result: Salai

**Convert to Myanmar Name**
input: Salai
response result: စလိုင်း
expected result: ဆလိုင်း

### How to reproduce the bug

**Convert to Myan-glish Name**
```php
$name = 'ဆလိုင်း';
MMName::convertToEn($name);
```

**Convert to Myanmar Name**
```php
$name = 'Salai'
MMName::convertToMm($name);
```

### Package Version

1.x

### PHP Version

8.2

### Laravel Version

10.x

### Which operating systems does with happen with?

macOS

**Comment by thantthuhein-genie** [comment]
Fixed in version 1.1.0
